name: Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test action
    steps:
      - name: ChatGPT review
        uses: detectiveCrow/ai-review-action@5-create-callable-js-module
        id: review
        with:
          OPENAI_API_KEY: "openai_test_api_key"

