name: Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    name: test action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ChatGPT review
        uses: ./
        id: review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: "korean"

      # - uses: anc95/ChatGPT-CodeReview@main
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #     # Optional
      #     LANGUAGE: Korean
