name: Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    name: test action
    steps:
      - name: ChatGPT review
        uses: detectiveCrow/ai-review-action@5-create-callable-js-module
        id: review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: "openai_test_api_key"
      # - uses: anc95/ChatGPT-CodeReview@main
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      #     # Optional
      #     LANGUAGE: Korean
